site_name: pingctl, A Ping Identity CLI
repo_name: pingidentity/pingctl
repo_url: https://github.com/pingidentity/pingctl
site_url: https://pingidentity.github.io/pingctl/
copyright: © Copyright 2021 Ping Identity
google_analytics: ['UA-156953351-1', 'devops.pingidentity.com']
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant

  palette:
   # scheme: preference
    primary: indigo
    accent: blue

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

nav:
  - pingctl:
      - Usage: index.md
      - Configuration: config.md
      - Release Notes: releasenotes.md
      - License: LICENSE.md
      - Disclaimer: DISCLAIMER.md
      - Contributing: CONTRIBUTING.md
  - Commands:
      - kubernetes: commands/kubernetes.md
      - license: commands/license.md
      - pingone: commands/pingone.md
